.ifndef TRACKS_INC
TRACKS_INC = 1

.global song_list
.global sfx_list
.global instrument_list
.global dpcm_list

MAX_TRACKS = 7

song_index_robot_adv = 0
song_index_k466 = 1
song_index_k11 = 2
song_index_soler42 = 3
song_index_antagonist = 4
song_index_arps = 5
song_index_noise_arps = 6

sfx_index_sfx_shot = 0
sfx_index_sfx_laser = 1
sfx_index_sfx_dpcm = 2
sfx_index_sfx_zap = 3
sfx_index_sfx_collide = 4

.endif
