.ifndef ZP_INC
ZP_INC = 1

.globalzp b0
.globalzp b1
.globalzp b2
.globalzp b3
.globalzp b4
.globalzp b5
.globalzp b6
.globalzp b7
.globalzp b8
.globalzp b9
.globalzp b10
.globalzp b11

.globalzp w0
.globalzp w1
.globalzp w2
.globalzp w3
.globalzp w4
.globalzp w5
.globalzp w6
.globalzp w7
.globalzp w8
.globalzp w9
.globalzp w10
.globalzp w11
.globalzp w12
.globalzp w13
.globalzp w14
.globalzp w15
.globalzp w16
.globalzp w17
.globalzp w18
.globalzp w19
.globalzp w20
.globalzp ppu_2000
.globalzp ppu_2001
.globalzp ppu_2005
.globalzp ppu_2006
.globalzp palette_address
.globalzp controller_buffer
.globalzp controller_routine
.globalzp vblank_routine
.globalzp vblank_done_flag
.globalzp current_song
.globalzp pause_flag
.globalzp next_sprite_address
.globalzp nmis

.endif
